# Generated by Django 4.2.11 on 2024-03-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('passcode', models.CharField(max_length=4)),
                ('timezone_name', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
